spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId:
          google:
            clientId:
            client-secret:
          naver:
            clientId:
            client-secret: