spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 6ddac36874fd18ac45d0c425d9b15b90
          google:
            clientId:
            client-secret:
          naver:
            clientId:
            client-secret: