spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: fbffa4e961a667f39079c6d200d601a9
          google:
            clientId: 91043027399-lc6s8pccjts8edjtmjberfrt2bhqpfgj.apps.googleusercontent.com
            client-secret: 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